CREATE DATABASE IF NOT EXISTS integrated1 CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE integrated1;

CREATE TABLE tasks (
    `id` INTEGER AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(100) NOT NULL,
    `description` VARCHAR(500),
    `assignees` VARCHAR(30),
    `status` ENUM('TO_DO', 'DOING', 'DONE', 'NO_STATUS') NOT NULL DEFAULT 'NO_STATUS',
    `createdOn` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`updatedOn` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
